language: elixir
elixir:
  - 1.3.0
  - 1.3.2
  - 1.3.3
  - 1.4.2
otp_release:
  - 18.0
  - 18.1
  - 18.2
  - 18.3
  - 19.0
sudo: false # to use faster container based build environment
cache:
  directories:
    - _build
    - deps
after_script:
  - mix deps.get
  - mix inch.report
notifications:
  recipients:
    - ges.jeremie@gmail.com