language: elixir
elixir:
  - 1.0.5
  - 1.1.1
  - 1.2.4
  - 1.3.0
otp_release:
  - 17.5
  - 18.0
  - 18.1
  - 18.2
  - 18.3
  - 19.0
sudo: false # to use faster container based build environment
cache:
  directories:
    - _build
    - deps
after_script:
  - mix deps.get
  - mix inch.report
notifications:
  recipients:
    - ges.jeremie@gmail.com
exclude:
  - otp_release: 17.5
    elixir: 1.2.4
  - otp_release: 17.5
    elixir: 1.3.1
  - otp_release: 19.0
    elixir: 1.1.1
  - otp_release: 19.0
    elixir: 1.0.5